lean_canvas_mvp: 
  description:
  expected_output:
  agent:
  inputs:


roadmap_mvp: 
  description:
  expected_output:
  agent:
  inputs:
  
prd_template: 
  description:
  expected_output:
  agent:
  inputs:
  
techstack_framework: 
  description:
  expected_output:
  agent:
  inputs:
