finding_target_audience:
  description: >
    You are tasked with generating a detailed list of target audience segments
    for a business based on the provided information.  Your goal is to create a
    comprehensive and specific list that will help the business focus its
    marketing efforts effectively. First, you will be given details about the
    business and a description of its products, services, or solutions. Read
    this information given by user as an input very carefully: 

    <startup_info>
    {STARTUP_INFO}
    </startup_info>

    Now, follow these steps to generate the target audience list:

    1. Analyze the business details and product description thoroughly. Consider
    the industry, market positioning, unique selling points, and any specific
    problems the product or service solves.

    2. Based on your analysis, identify potential customer segments that would
    benefit from or be interested in the product or service. Consider factors
    such as:
      - Demographics (age, gender, income level, education, occupation)
      - Psychographics (lifestyle, values, interests, attitudes)
      - Behavioral characteristics (purchasing habits, brand loyalty, usage rate)
      - Geographic location (if relevant)

    3. For each identified segment, think about specific sub-segments or niches
    that could be targeted. Be as detailed and specific as possible.

    4. Consider both primary and secondary target audiences. Primary audiences
    are those most likely to purchase or use the product/service, while
    secondary audiences might influence the decision-makers or benefit
    indirectly.

    5. Ensure that each target audience segment is relevant to the business and
    product/service offered.

    Remember to be as detailed and specific as possible when describing each
    audience segment.  Avoid broad, generic categories and instead focus on
    well-defined niches that align closely with the business and its offerings. 
    Aim to provide at least 3 primary audience segments and 3 secondary
    audience segments, but adjust based on the complexity and scope of the
    business
  expected_output: >
    <target_audience>
    <Primary_TG1>
    Primary Audiences Target Group 1
    Top 3 specific characteristics of the Primary Audiences Target Group 1
    Reasons summary why this segment is a good fit
    </Primary_TG1>
    <Primary_TG2>
    2. Primary Audiences Target Group 2
    Top 3 specific characteristics of the Primary Audiences Target Group 2
    Reasons summary why this segment is a good fit
    </Primary_TG2>
    <Primary_TG3>
    3. Primary Audiences Target Group 3
    Top 3 specific characteristics of the Primary Audiences Target Group 3
    Reasons summary why this segment is a good fit
    </Primary_TG3>
    [Continue with additional primary segments as needed]
    <Secondary_TG1>
    Secondary Audiences Target Group 1:
    Top 3 specific characteristics of the Secondary Audiences Target Group 1
    Reasons why this segment is relevant
    </Secondary_TG1>
    <Secondary_TG2>
    Secondary Audiences Target Group 2:
    Top 3 specific characteristics of the Secondary Audiences Target Group 2
    Reasons why this segment is relevant
    </Secondary_TG2>
    <Secondary_TG3>
    Secondary Audiences Target Group 3:
    Top 3 specific characteristics of the Secondary Audiences Target Group 3
    Reasons why this segment is relevant
    </Secondary_TG3>
    [Continue with additional secondary segments as needed]
    </target_audience>
  agent: TargetAudienceAgent