product_audience_fit: 
  description:
  expected_output:
  agent:
  inputs:


marketing_4p_analysis: 
  description:
  expected_output:
  agent:
  inputs:
  
swot_analysis: 
  description:
  expected_output:
  agent:
  inputs:
  
mapping_buyer_journey: 
  description:
  expected_output:
  agent:
  inputs:
  
usp_rose_framework: 
  description:
  expected_output:
  agent:
  inputs:
  