value_proposition_canvas: 
  description: >
    You are tasked with conducting a Stages of Awareness analysis based on the provided information about a target audience, buyer persona, motivations and desired outcomes, business details, and product/service/solutions details. The Stages of Awareness concept, developed by Eugene Schwartz, helps understand how aware potential customers are of their problems and the available solutions.

    Here is the information of the startup you'll be working with:

    <startup_info>
    {STARTUP_INFO}
    </startup_info>

    Using this information, analyze the target audience's awareness level across the following stages:

    1. Unaware: The audience doesn't know they have a problem.
    2. Problem Aware: They know they have a problem but don't know there's a solution.
    3. Solution Aware: They know a solution exists but don't know about the specific product/service.
    4. Product Aware: They know about the product/service but aren't sure if it's right for them.
    5. Most Aware: They know a lot about the product/service and are almost ready to buy.

    For each stage, consider:
    - What percentage of the target audience might be in this stage?
    - What key messages or information would resonate with people in this stage?
    - What marketing channels or tactics might be most effective for reaching people in this stage?
    Ensure that your analysis is thorough, insightful, and directly relates to the provided information about the 
    target audience, buyer persona, motivations, business, and product/service details.

  expected_output: >
    <value_proposition_canvas>
    <customer_profile>
    <customer_jobs>
    [List 3-5 customer jobs]
    </customer_jobs>
    <customer_pains>
    [List 3-5 customer pains]
    </customer_pains>
    <customer_gains>
    [List 3-5 customer gains]
    </customer_gains>
    </customer_profile>

    <value_map>
    <pain_relievers>
    [List 3-5 pain relievers]
    </pain_relievers>
    <gain_creators>
    [List 3-5 gain creators]
    </gain_creators>
    <products_and_services>
    [List key features or aspects of the product/service]
    </products_and_services>
    </value_map>

    <fit_evaluation>
    [Provide a brief analysis of how well the product/service fits with the customer's needs]
    </fit_evaluation>
    </value_proposition_canvas>


  agent: ValuePropCanvasAgent

marketing_4p_analysis: 
  description: >
    You are a marketing analyst tasked with applying the 4Ps of Marketing framework (Product, Price, Place, Promotion) to help understand a target audience and how a 
    product/service aligns with their needs. You will be provided with information about the target audience and the product/service, and you should use this information to answer 
    a series of questions about each of the 4Ps.

    First, carefully read and analyze the following information about the startup

    <startup_info>
    {STARTUP_INFO}
    </startup_info>
   
    Using the provided information, answer the following questions for each of the 4Ps. Be sure to base your answers on the specific details given about the target audience and product/service. If there isn't enough information to answer a question fully, make reasonable assumptions based on the available data and clearly state that you are making an assumption.

    For each of the 4Ps, provide your analysis inside the corresponding JSON Key following the pydantic. Within each key, use subheadings (e.g., ) 
    to separate your answers to individual questions.
    Remember to base all your answers on the provided information about the target audience and product/service. 
    If you need to make any assumptions, clearly state them in your analysis.
  expected_output: >
    <marketing_4ps>
     
      <4p_product>
        <problem_solved>
        [Analyze what problem the product/service solves for the target audience]

        <competitive_advantage>
        [Explain how the product/service stands out compared to competitors' offerings]

        <key_features_benefits>
        [Identify the key features or benefits that are most important to the target audience]
      </4p_product>

      <4p_price>
        <pricing_model>
        [Recommend a pricing model that would appeal most to the target audience]

        <perceived_value>
        [Analyze how the target audience perceives the value of the product/service relative to its price]

        <price_sensitivities>
        [Identify any specific price sensitivities within the target audience]
      </4p_price>

      <4p_place>
        <solution_seeking_behavior>
        [Describe where the target audience typically seeks solutions like this product/service]

        <distribution_channels>
        [Recommend which distribution channels or platforms would best reach the target audience]

        <accessibility>
        [Suggest how to make the product/service easily accessible to the target audience]
      </4p_place>

      <4p_promotion>
        <marketing_messages>
        [Describe what types of marketing messages and content would resonate most with the target audience]

        <advertising_channels>
        [Recommend which advertising channels should be focused on to capture the target audience's attention]

        <messaging_style>
        [Suggest what tone, style, or language should be used in messaging to appeal to the target audience]
      </4p_promotion>

    </marketing_4ps>

  agent: Market4PAnalysisAgent
  
swot_analysis: 
  description: >
   You are tasked with conducting a SWOT (Strengths, Weaknesses, Opportunities, Threats) analysis for a target audience. 
   This analysis will help create more targeted and effective marketing strategies. Follow these instructions carefully to complete the task.

    First, here is the description of the target audience you will be analyzing:

    <startup_info>
    {STARTUP_INFO}
    </startup_info>

    Now, follow these steps to conduct the SWOT analysis:

    1. Carefully read and analyze the target audience description.

    2. For each component of the SWOT analysis, consider the following:

      a) Strengths:
      - Identify key strengths of the target audience that align with a product or service.
      - Determine what motivates them to buy (e.g., high purchasing power, brand loyalty).
      - Note positive behaviors that make them ideal customers.

      b) Weaknesses:
      - Identify weaknesses or pain points of the target audience.
      - Consider potential challenges or objections they might have when considering a product/service.
      - Note any barriers to purchasing (e.g., limited budget, lack of trust, long decision-making process).

      c) Opportunities:
      - Identify opportunities in the market that could help engage with this audience better.
      - Consider unmet needs or trends that could be leveraged (e.g., digital adoption, desire for sustainability).
      - Look for growing demands or underserved niches within this audience.

      d) Threats:
      - Identify external threats that could affect the ability to reach or convert this audience.
      - Consider competitors that might be better positioned to meet their needs.
      - Note any industry shifts, regulations, or market trends that could negatively impact the relationship with this audience.

    3. Based on your analysis, fill out the following SWOT table:
    4. For each component in the SWOT table, provide at least three detailed insights based on the target audience description. Ensure that each insight is specific, relevant, and actionable.

    5. After completing the table, provide a brief summary in swot_summary json key (2-3 sentences) of the key findings from your SWOT analysis and how 
    they can be used to create more targeted and effective marketing strategies.

    Present your completed SWOT analysis, including the filled table and summary, within "swot_analysis" JSON key.


  expected_output: >
    
    <swot_analysis>
    | SWOT Component | Insights for Target Audience |
    |-----------------|------------------------------|
    | Strengths       |                              |
    | Weaknesses      |                              |
    | Opportunities   |                              |
    | Threats         |                              |
    </swot_analysis>
    
  agent: SWOTAnalysisAgent
  
mapping_buyer_journey: 
  description: >
    You are tasked with mapping out the Buyer's Journey for a specific target audience and product/service.
    Your goal is to provide insights into how the target audience moves through each stage of the journey, from becoming aware of their problem to purchasing 
    the product/service and beyond.

    First, review the following information about the startup:

    <startup_info>
    {STARTUP_INFO}
    </startup_info>

    Now, follow these steps to complete the Buyer's Journey mapping:

    1. Awareness Stage:
      - Identify common challenges or pain points the target audience faces.
      - Describe how they typically discover they have this problem.
      - List where they seek information about their problem.
      - Provide examples of questions they might ask at this stage.

    2. Consideration Stage:
      - List potential solutions the audience might consider, including competitors.
      - Identify key decision-making criteria for the audience.
      - Describe concerns or hesitations they may have about choosing a solution.
      - Suggest how to position the product/service to meet their criteria.

    3. Decision Stage:
      - Identify final information or reassurance the audience needs before committing.
      - List factors that could push them to choose the product/service.
      - Specify the desired action for the audience to take.
      - Suggest ways to make the buying process easier for them.

    4. Post-Purchase Stage:
      - Describe the experience or result the audience expects after purchasing.
      - Suggest ways to ensure customer satisfaction or exceed expectations.
      - Identify opportunities for encouraging repeat business or referrals.

    For each stage, provide at least one key insight that can be used in a lead generation strategy.

  expected_output: >
    <buyers_journey>
    <awareness_stage>
    [Include your analysis and insights for the Awareness Stage here]
    </awareness_stage>

    <consideration_stage>
    [Include your analysis and insights for the Consideration Stage here]
    </consideration_stage>

    <decision_stage>
    [Include your analysis and insights for the Decision Stage here]
    </decision_stage>

    <post_purchase_stage>
    [Include your analysis and insights for the Post-Purchase Stage here]
    </post_purchase_stage>

    <key_insights>
    [Include at least one key insight for each stage that can be used in a lead generation strategy and i need string output]
    </key_insights>
    </buyers_journey>


  agent: MappingBuyerJourneyAgent

usp_rose_framework: 
  description: >
    These are the details about the startup go through it below:

    <startup_info>
    {STARTUP_INFO}
    </startup_info>

    You are a marketing expert tasked with applying the ROSE framework (Relevant - How does it connect to customer 
    needs?; Original - What makes it different from competitors?; Simple - Can it be communicated clearly?; 
    Emotional - How does it resonate with customer feelings?) to analyse and recommend the top 3 USPs and MOAT of the startup from the 
    above data provided.
    Ensure that your analysis is thorough, insightful, and directly relates to the provided target audience,
    idea, product, customer persona and value proposition given above.
  expected_output: >
    <rose_analysis>
    <rose_relevant>
    [List the relevant analysis]
    </rose_relevant>
    <rose_original>
    [List the original analysis]
    </rose_original>
    <rose_simple>
    [List the simple analysis]
    </rose_simple>
    <rose_emotional>
    [List the emotional analysis]
    </rose_emotional>
    </rose_analysis>
    <rose_USPs>
    [USP 1]
    [USP 2]
    [USP 3]
    </rose_USPs>
    <rose_moat>
    [List the Moat]
    </rose_moat>
    <rose_implementation_strategy>
    [List the implementation strategy]
    </rose_implementation_strategy>
    <rose_success_metric>
    [List the success metrics]
    </rose_success_metric>
    <rose_summary>
    [Summary of the USP]
    </rose_summary>
  agent: USPRoseFrameworkAgent
  