market_readiness: 
  description:
  expected_output:
  agent:
  inputs:


technology_adoption_specilist: 
  description:
  expected_output:
  agent:
  inputs:
  
risk_assessment_specialist: 
  description:
  expected_output:
  agent:
  inputs:
  
blue_ocean_specialist: 
  description:
  expected_output:
  agent:
  inputs:

  