brand_story:
  description: >
    You are tasked with crafting a compelling brand story using the Story Brand Framework. This framework positions the target audience as the hero and the brand as the guide, solving their core problems and helping them achieve their goals.

    First, carefully read and analyze the following brand information:

    <brand_info>
    
    {{BRAND_INFO}}
    
    </brand_info>

    Now, follow these steps to craft the brand story:

    1. Analyze the provided brand information, identifying key elements that align with each section of the Brand Story Framework:
      - Hero (Target Audience)
      - The Problem
      - Your Brand as the Guide
      - The Call to Action
      - The Result (Success)

    2. For each section of the framework, extract relevant details from the brand information and organize them according to the framework's structure.

    3. Craft a cohesive brand story that flows naturally from one section to the next, ensuring that:
      - The target audience is positioned as the hero of the story
      - The brand is presented as the guide that helps the hero overcome challenges
      - The narrative focuses on how the brand helps the audience achieve success

    4. Review your brand story to ensure it addresses all key points in the framework and effectively communicates the brand's value proposition.


  expected_output: >
    Provide your completed brand story in the following format:

    <brand_story>
    <hero>
    [Describe the target audience, their characteristics, pain points, and aspirations]
    </hero>

    <problem>
    [Outline the specific problem the audience faces, its impact, and potential consequences]
    </problem>

    <guide>
    [Explain how the brand serves as a guide, its unique positioning, and the solution it offers]
    </guide>

    <call_to_action>
    [Clearly state the desired action for the audience to take]
    </call_to_action>

    <result>
    [Describe the positive outcome and success the audience will experience]
    </result>
    </brand_story>

    Ensure that each section of your brand story is concise yet comprehensive, capturing the essence of the brand and its relationship with the target audience. Focus on creating a narrative that resonates with the audience and clearly communicates the brand's value.


  agent: BrandStoryAgent

market_message_aida:
  description: >
    You are tasked with creating a message sequence using the AIDA (Attention, Interest, Desire, Action) framework for a specific product or service targeting a particular audience. Follow these steps carefully:

    1. First, review the information about your target audience:
    <target_audience>
    {{TARGET_AUDIENCE}}
    </target_audience>

    2. Next, familiarize yourself with the product or service you're promoting:
    <product_description>
    {{PRODUCT_DESCRIPTION}}
    </product_description>

    3. Now, create a message sequence using the AIDA framework. For each step, provide a brief explanation of your reasoning followed by the actual message content. Use the following structure:

    <attention>
    Reasoning: [Explain why this will grab the audience's attention]
    Message: [Write the attention-grabbing headline or message]
    </attention>

    <interest>
    Reasoning: [Explain how this builds interest]
    Message: [Write the content that builds interest]
    </interest>

    <desire>
    Reasoning: [Explain how this creates desire]
    Message: [Write the content that creates desire]
    </desire>

    <action>
    Reasoning: [Explain why this call-to-action is effective]
    Message: [Write the clear and specific call-to-action]
    </action>

    4. After completing all four steps of the AIDA framework, provide a brief summary of how your message sequence aligns with the target audience and effectively promotes the product or service.

    Remember to tailor each step to the specific characteristics and needs of your target audience, and ensure that your messages highlight the unique value proposition of your product or service.

  expected_output: >
    Present your final output in the following format:
    <aida_framework>
    [Insert your completed AIDA framework here, including all four steps with reasoning and messages]
    </aida_framework>

    <summary>
    [Insert your brief summary here]
    </summary>

  agent: MarketMessageAgent

platform_selection:
  description: >
    You are tasked with identifying the best platforms and channels to reach a specific target audience effectively. Your objective is to analyze the given target audience description and recommend the most suitable digital platforms and channels for engagement.

    Here is the description of the target audience:
    <target_audience>
    {{TARGET_AUDIENCE}}
    </target_audience>

    Carefully analyze the provided target audience description. Pay attention to demographics, psychographics, job roles (if applicable), online behavior, goals, pain points, and content preferences.

    Based on your analysis, identify the most appropriate digital platforms and channels where this target audience is likely to be active and receptive. Consider social media platforms, email marketing, search engines, content platforms, forums, and any other relevant channels.

    For each recommended platform or channel, provide a brief explanation of why it's suitable for this specific target audience. Consider factors such as:
    - The audience's typical online behavior
    - Types of content they prefer
    - How the platform aligns with their goals and pain points
    - The potential for engagement on the platform

    Also, consider how success can be measured on these platforms. Suggest relevant key performance indicators (KPIs) that could be used to track the effectiveness of engagement efforts.

  expected_output: >
   Present your recommendations and analysis in a clear, structured format. Use bullet points or numbered lists where appropriate to enhance readability.

    Begin your response with:
    <platform_recommendations>

    End your response with:
    </platform_recommendations>

    Within your response, clearly label each section, such as "Recommended Platforms," "Justification," and "Suggested KPIs."

  agent: PlatformSlecetionAgent

lead_stages:
  description: >
   You are tasked with creating a series of lead stages for a business. This will help outline the customer journey from initial awareness to final conversion. Follow these instructions carefully to create a comprehensive lead stage breakdown.

    First, you will be given two pieces of information:

    <business_details>
    {{BUSINESS_DETAILS}}
    </business_details>

    <target_audience>
    {{TARGET_AUDIENCE}}
    </target_audience>

    Using this information, create a series of lead stages that are appropriate for the given business details and target audience. Your lead stages should include the following:

    1. Awareness
    2. Interest
    3. Consideration
    4. Decision
    5. Action

    For each stage, provide the following information:

    a) Target Audience Behavior: Describe how the audience typically encounters or interacts with the business at this stage.
    b) What They're Thinking: Outline the main questions or concerns the audience might have at this stage.
    c) Content Needed: Suggest types of content that would be most effective at this stage.
    d) Call to Action: Recommend an appropriate action for the audience to take to move to the next stage.

  expected_output: >
    Present your lead stages in the following format:

    <lead_stages>
    <stage_name>Stage Name</stage_name>
    <audience_behavior>Description of audience behavior</audience_behavior>
    <audience_thoughts>What the audience is thinking</audience_thoughts>
    <content_ideas>Suggested content for this stage</content_ideas>
    <call_to_action>Recommended action for the audience</call_to_action>
    </lead_stages>

    Repeat this structure for all five stages.

    After presenting all stages, provide a brief summary of how these stages form a cohesive customer journey, tailored to the specific business details and target audience.

    Finally, end your response with an example prompt that a business owner could use to generate these lead stages using an AI tool. Format it like this:

    <example_prompt>
    Your example prompt here
    </example_prompt>

    Remember to tailor all aspects of your response to the specific business details and target audience provided.

  agent: LeadStagesAgent

lead_qualification_checklist:
  description: >
    You are tasked with creating a Lead Qualification Checklist for a business. This checklist will help the business prioritize leads that are most likely to convert. Follow these instructions carefully to complete the task:

    1. You will be provided with two pieces of information:
    <business_details>
    {{BUSINESS_DETAILS}}
    </business_details>

    <target_audience>
    {{TARGET_AUDIENCE}}
    </target_audience>

    2. Analyze the business description and target audience information carefully.

    3. Based on this analysis, create a Lead Qualification Checklist that includes specific criteria for qualifying leads. Consider the following elements:
      - Budget: Does the lead have the financial capacity to purchase the product/service?
      - Authority: Is the lead a decision-maker or influencer in their organization?
      - Need: Does the lead have a clear need for the product/service?
      - Timeline: Is there a specific timeframe for making a purchase decision?
      - Fit: How well does the lead align with the ideal customer profile?

    4. For each element, create 1-3 specific, relevant questions or criteria that will help qualify the lead.

  expected_output: >
   Present your Lead Qualification Checklist in the following format:
    <lead_qualification_checklist>
    1. [Element Name]
        - [Criterion 1]
        - [Criterion 2]
        - [Criterion 3]

    2. [Element Name]
        - [Criterion 1]
        - [Criterion 2]
        ...
    </lead_qualification_checklist>

   After the checklist, provide a brief explanation (2-3 sentences) of how this checklist is tailored to the specific business and target audience.

    Here's an example of a well-structured response:

    <lead_qualification_checklist>
    1. Budget
      - Does the lead have an annual revenue of at least $500,000?
      - Is their budget for this solution at least $10,000?

    2. Authority
      - Is the lead a C-level executive or department head?
      - Do they have final say in purchasing decisions?

    3. Need
      - Has the lead expressed challenges that our product can solve?
      - Are they currently using a competitor's product?

    4. Timeline
      - Is the lead looking to implement a solution within the next 6 months?
      - Do they have an upcoming project that requires our product?

    5. Fit
      - Does the lead's company size fall within our target range of 50-500 employees?
      - Is the lead's industry one of our key target sectors?
    </lead_qualification_checklist>

    This Lead Qualification Checklist is tailored to a B2B SaaS company targeting mid-sized businesses in specific industries. The criteria focus on identifying leads with sufficient budget, decision-making authority, and a clear need for the product, while also ensuring they fit the company's ideal customer profile.

    Remember to customize your checklist based on the specific business description and target audience provided. Your goal is to create a practical and effective tool for qualifying leads that are most likely to convert for this particular business.

  agent: LeadQualificationAgent